CREATE TABLE [dbo].[Users](
	[ID] int NOT NULL IDENTITY(0,1) PRIMARY KEY,
	[FirstName] nvarchar(50) NOT NULL,
	[MiddleName] nvarchar(50) NULL,
	[LastName] nvarchar(50) NOT NULL,
	[UserName] nvarchar(50) NOT NULL,
	[PrimaryPersonalEmail] varchar(320) NOT NULL,
	[EmailValidated] bit NOT NULL DEFAULT (0),
	[PrimaryPhone] varchar(15) NOT NULL,
	[PhoneValidated] bit NOT NULL DEFAULT (0),
	[KeepPrivate] bit NOT NULL DEFAULT (0),
	[MetricOverImperial] bit NOT NULL DEFAULT (1),
	[CountryID] tinyint NULL DEFAULT (NULL),
	[ProvinceID] smallint NULL DEFAULT (NULL),
	[AccessLevelID] tinyint NOT NULL DEFAULT (5),
	[HashedPassword] nchar(44) NOT NULL,
	[Salt] [char](44) NOT NULL,
	[ProfilePictureBytes] varbinary(max) NULL,
	[BannerPictureBytes] varbinary(max) NULL,
	[Bio] nvarchar(2500) NULL,
	[ProfileURL] nvarchar(100) NULL,

	CONSTRAINT [UQ_PrimaryPhone] UNIQUE NONCLUSTERED ([PrimaryPhone]),
	CONSTRAINT [UQ_UserName] UNIQUE NONCLUSTERED ([UserName]),
	CONSTRAINT [UQ_PrimaryPersonalEmail] UNIQUE NONCLUSTERED ([PrimaryPersonalEmail]),

	CONSTRAINT [FK_UserAccessTokens_UserAccessLevels] FOREIGN KEY([AccessLevelID]) REFERENCES [dbo].[UserAccessLevels] ([ID]),
	CONSTRAINT [FK_Users_Countries] FOREIGN KEY([CountryID]) REFERENCES [dbo].[Countries] ([ID]),
	CONSTRAINT [FK_Users_ProvincesOrStates] FOREIGN KEY([ProvinceID]) REFERENCES [dbo].[ProvincesOrStates] ([ID]),
)