CREATE TABLE [dbo].[RockClimbingWalls](
	[AreaId] int NOT NULL,
	[Id] int NOT NULL PRIMARY KEY IDENTITY(0,1),
	[EnglishFullName] varchar(100) NOT NULL,
	[WallCode] [char](5) NOT NULL,
	[Approach] [varchar](50) NOT NULL DEFAULT ('Unknown'),
	[LatitudeStartOrCenter] [float] NULL,
	[LongitudeStartOrCenter] [float] NULL,
	[LatitudeParking] [float] NULL,
	[LongitudeParking] [float] NULL,
	[ThumbPictureBytes] [varbinary](max) NULL,
	[Info] [varchar](5000) NULL,
	[JanSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[FebSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[MarSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[AprSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[MaySeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[JunSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[JulSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[AugSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[SepSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[OctSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[NovSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[DecSeasonalClimbingQualityRatingId] [tinyint] NOT NULL DEFAULT (0),
	[JanSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[FebSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[MarSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[AprSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[MaySeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[JunSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[JulSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[AugSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[SepSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[OctSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[NovSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),
	[DecSeasonalBusyRatingId] [tinyint] NOT NULL DEFAULT (0),

	CONSTRAINT [UQ_RockClimbingWalls_Code] UNIQUE ([AreaId], [WallCode]),
	CONSTRAINT [UQ_RockClimbingWalls_Name] UNIQUE ([AreaId], [EnglishFullName]),

	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Apr] FOREIGN KEY([AprSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Aug] FOREIGN KEY([AugSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Dec] FOREIGN KEY([DecSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Feb] FOREIGN KEY([FebSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Jan] FOREIGN KEY([JanSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Jul] FOREIGN KEY([JulSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Jun] FOREIGN KEY([JunSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Mar] FOREIGN KEY([MarSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_May] FOREIGN KEY([MaySeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Nov] FOREIGN KEY([NovSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Oct] FOREIGN KEY([OctSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Sep] FOREIGN KEY([SepSeasonalBusyRatingId]) REFERENCES [dbo].[BusyRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Apr] FOREIGN KEY([AprSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Aug] FOREIGN KEY([AugSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Dec] FOREIGN KEY([DecSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Feb] FOREIGN KEY([FebSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Jan] FOREIGN KEY([JanSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Jul] FOREIGN KEY([JulSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Jun] FOREIGN KEY([JunSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Mar] FOREIGN KEY([MarSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_May] FOREIGN KEY([MaySeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Nov] FOREIGN KEY([NovSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Oct] FOREIGN KEY([OctSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Sep] FOREIGN KEY([SepSeasonalClimbingQualityRatingId]) REFERENCES [dbo].[ClimbingQualityRatings] ([Id]),
	CONSTRAINT [FK_RockClimbingWalls_Areas] FOREIGN KEY([AreaId]) REFERENCES [dbo].[Areas] ([Id]),

	CONSTRAINT [CK_RockClimbingWalls_LatitudeStartOrCenter_Max] CHECK ([LatitudeStartOrCenter]<=90),
	CONSTRAINT [CK_RockClimbingWalls_LatitudeStartOrCenter_Min] CHECK ([LatitudeStartOrCenter]>=-90),
	CONSTRAINT [CK_RockClimbingWalls_LongitudeStartOrCenter_Max] CHECK ([LatitudeStartOrCenter]<=180),
	CONSTRAINT [CK_RockClimbingWalls_LongitudeStartOrCenter_Min] CHECK ([LatitudeStartOrCenter]>=-180),
)

