CREATE TABLE [dbo].[RockClimbingWalls](
	[AreaID] int NOT NULL,
	[ID] int NOT NULL PRIMARY KEY IDENTITY(0,1),
	[EnglishFullName] varchar(100) NOT NULL,
	[WallCode] [char](5) NOT NULL,
	[Approach] [varchar](50) NOT NULL DEFAULT ('Unknown'),
	[LatitudeStartOrCenter] [float] NULL,
	[LongitudeStartOrCenter] [float] NULL,
	[LatitudeParking] [float] NULL,
	[LongitudeParking] [float] NULL,
	[ThumbPictureBytes] [varbinary](max) NULL,
	[Info] [varchar](5000) NULL,
	[JanSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[FebSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[MarSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[AprSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[MaySeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[JunSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[JulSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[AugSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[SepSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[OctSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[NovSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[DecSeasonalClimbingQualityRatingID] [tinyint] NOT NULL DEFAULT (0),
	[JanSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[FebSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[MarSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[AprSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[MaySeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[JunSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[JulSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[AugSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[SepSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[OctSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[NovSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),
	[DecSeasonalBusyRatingID] [tinyint] NOT NULL DEFAULT (0),

	CONSTRAINT [UQ_RockClimbingWalls_Code] UNIQUE ([AreaID], [WallCode]),
	CONSTRAINT [UQ_RockClimbingWalls_Name] UNIQUE ([AreaID], [EnglishFullName]),

	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Apr] FOREIGN KEY([AprSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Aug] FOREIGN KEY([AugSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Dec] FOREIGN KEY([DecSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Feb] FOREIGN KEY([FebSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Jan] FOREIGN KEY([JanSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Jul] FOREIGN KEY([JulSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Jun] FOREIGN KEY([JunSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Mar] FOREIGN KEY([MarSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_May] FOREIGN KEY([MaySeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Nov] FOREIGN KEY([NovSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Oct] FOREIGN KEY([OctSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_BusyRatings_Sep] FOREIGN KEY([SepSeasonalBusyRatingID]) REFERENCES [dbo].[BusyRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Apr] FOREIGN KEY([AprSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Aug] FOREIGN KEY([AugSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Dec] FOREIGN KEY([DecSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Feb] FOREIGN KEY([FebSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Jan] FOREIGN KEY([JanSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Jul] FOREIGN KEY([JulSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Jun] FOREIGN KEY([JunSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Mar] FOREIGN KEY([MarSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_May] FOREIGN KEY([MaySeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Nov] FOREIGN KEY([NovSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Oct] FOREIGN KEY([OctSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_ClimbingQualityRatings_Sep] FOREIGN KEY([SepSeasonalClimbingQualityRatingID]) REFERENCES [dbo].[ClimbingQualityRatings] ([ID]),
	CONSTRAINT [FK_RockClimbingWalls_Areas] FOREIGN KEY([AreaID]) REFERENCES [dbo].[Areas] ([ID]),

	CONSTRAINT [CK_RockClimbingWalls_LatitudeStartOrCenter_Max] CHECK ([LatitudeStartOrCenter]<=90),
	CONSTRAINT [CK_RockClimbingWalls_LatitudeStartOrCenter_Min] CHECK ([LatitudeStartOrCenter]>=-90),
	CONSTRAINT [CK_RockClimbingWalls_LongitudeStartOrCenter_Max] CHECK ([LatitudeStartOrCenter]<=180),
	CONSTRAINT [CK_RockClimbingWalls_LongitudeStartOrCenter_Min] CHECK ([LatitudeStartOrCenter]>=-180),
)

